// Shared data for all gallery pages — edit titles/prices/availability here.
var ARTIST_EMAIL = "susang7@hotmail.com";

var PAINTINGS = [
  { src: "paintings/susan-115.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-248.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-44.jpg", title: "Pink Ranunculus", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-460.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-208.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-33.jpg", title: "Pink Blossoms", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-122.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-109.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-378.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-102.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-41.jpg", title: "Crimson Poppies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-468.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-203.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-22.jpg", title: "Birds of Paradise", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-364.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-47.jpg", title: "Single Daisy", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-35.jpg", title: "White Lilies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-335.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-05.jpg", title: "White Magnolia", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-154.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-127.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-13.jpg", title: "Cherry Blossoms", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-40.jpg", title: "Red Tulips", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-376.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-443.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-206.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-34.jpg", title: "Peach Blossoms", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-336.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-37.jpg", title: "White Poppies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-229.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-14.jpg", title: "Spring Branches", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-377.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-117.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-25.jpg", title: "Yellow Freesia", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-149.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-366.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-52.jpg", title: "Pink Hibiscus", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-42.jpg", title: "Black-Eyed Susans", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-292.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-18.jpg", title: "Wildflowers", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-433.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-111.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-495.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-11.jpg", title: "Red Geraniums", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-160.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-246.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-53.jpg", title: "Daisies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-104.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-182.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-245.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-101.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-38.jpg", title: "Red Poppies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-363.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-140.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-121.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-400.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-465.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-60.jpg", title: "Peonies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-46.jpg", title: "Evening Vase", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-138.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-243.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-242.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-01.jpg", title: "Iris", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-204.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-32.jpg", title: "White Blossoms", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-230.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-450.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-386.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-155.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-341.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-49.jpg", title: "Red Poppies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-50.jpg", title: "Tulips in Bloom", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-368.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-205.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-306.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-07.jpg", title: "Cotton Blossoms", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-130.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-158.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-152.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-106.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-369.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-375.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-143.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-346.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-159.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-201.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-31.jpg", title: "White Daisies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-132.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-153.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-06.jpg", title: "Black-Eyed Susans", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-120.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-250.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-03.jpg", title: "Poppies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-339.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-496.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-27.jpg", title: "Sunflowers", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-02.jpg", title: "Anemones", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-498.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-365.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-128.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-402.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-391.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-224.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-163.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-362.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-21.jpg", title: "Bird of Paradise II", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-36.jpg", title: "Fuchsia", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-114.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-54.jpg", title: "Apple Blossoms", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-448.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-146.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-379.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-10.jpg", title: "Golden Daffodil", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-16.jpg", title: "Red Blooms", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-233.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-135.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-222.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-04.jpg", title: "Red Amaryllis", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-326.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-56.jpg", title: "Water Lilies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-331.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-415.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-45.jpg", title: "Spring Daffodils", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-411.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-15.jpg", title: "Blossom Branch", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-392.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-247.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-118.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-162.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-322.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-249.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-151.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-345.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-342.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-467.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-214.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-469.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-59.jpg", title: "Red Roses", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-24.jpg", title: "Pink Coneflower", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-20.jpg", title: "Bird of Paradise", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-51.jpg", title: "Yellow Poppies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-179.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-145.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-48.jpg", title: "Lavender", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-225.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-17.jpg", title: "Pink Protea", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-110.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-57.jpg", title: "Sunflower", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-202.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-131.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-157.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-125.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-150.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-383.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-466.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-340.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-09.jpg", title: "Evening Blossoms", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-156.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-144.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-105.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-164.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-43.jpg", title: "Daffodils", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-161.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-133.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-136.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-166.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-08.jpg", title: "Pink Tulips", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-26.jpg", title: "Cactus Bloom", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-240.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-129.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-55.jpg", title: "Tulips", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-403.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-380.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-58.jpg", title: "Pansies", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-12.jpg", title: "Scarlet Blooms", medium: "Watercolour", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-232.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-497.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-241.jpg", title: "Floral Study", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-478.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-493.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-261.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-314.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-181.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-429.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-287.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-174.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-420.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-293.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-325.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-298.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-489.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-482.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-502.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-307.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-506.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-434.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-449.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-310.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-305.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-286.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-473.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-486.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-408.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-452.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-475.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-470.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-281.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-236.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-424.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-257.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-343.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-297.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-477.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-308.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-393.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-485.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-295.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-303.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-505.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-503.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-382.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-484.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-291.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-294.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-488.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-453.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-483.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-235.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-419.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-428.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-282.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-126.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-259.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-480.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-299.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-423.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-463.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-431.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-479.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-355.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-300.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-237.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-425.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-432.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-139.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-504.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-258.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-283.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-354.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-238.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-278.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-353.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-296.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-304.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-285.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-352.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-472.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-471.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-430.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-476.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-260.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-494.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-492.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-301.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-284.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-280.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-474.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-491.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-421.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-481.jpg", title: "Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-427.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-309.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-169.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-274.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-212.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-422.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-446.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-219.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-190.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-213.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-464.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-441.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-124.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-344.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-318.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-435.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-192.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-103.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-189.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-116.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-175.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-437.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-113.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-358.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-269.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-273.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-338.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-319.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-316.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-279.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-348.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-397.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-218.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-254.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-384.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-141.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-337.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-361.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-207.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-252.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-272.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-220.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-370.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-266.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-320.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-456.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-438.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-371.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-221.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-324.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-171.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-401.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-264.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-231.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-317.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-268.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-267.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-209.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-367.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-262.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-255.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-244.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-445.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-215.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-211.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-176.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-256.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-142.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-228.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-172.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-312.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-270.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-170.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-217.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-381.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-360.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-263.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-357.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-458.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-442.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-107.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-457.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-447.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-265.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-311.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-227.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-323.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-347.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-223.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-426.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-271.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-180.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-540.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-412.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-534.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-399.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-535.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-351.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-532.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-372.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-436.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-526.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-387.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-398.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-528.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-395.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-356.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-536.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-374.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-418.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-413.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-533.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-359.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-330.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-216.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-531.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-112.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-530.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-455.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-541.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-405.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-542.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-537.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-404.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-406.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-373.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-200.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-538.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-394.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-459.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-407.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-539.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-543.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-527.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-410.jpg", title: "Scene", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-529.jpg", title: "Town", medium: "", price: "Inquire", sold:false, cat:"Towns" },
  { src: "paintings/susan-524.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-188.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-501.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-522.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-389.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-521.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-199.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-239.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-513.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-186.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-321.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-519.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-515.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-409.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-187.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-514.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-444.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-276.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-417.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-185.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-525.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-178.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-520.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-517.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-516.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-147.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-196.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-184.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-416.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-523.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-511.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:true, cat:"Animals" },
  { src: "paintings/susan-510.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-451.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-414.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-195.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-512.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-454.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-191.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-518.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-508.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-509.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-198.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-461.jpg", title: "Wildlife", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-289.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-253.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-350.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-183.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-396.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-349.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-251.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-123.jpg", title: "Figure", medium: "", price: "Inquire", sold:true, cat:"Abstract" },
  { src: "paintings/susan-327.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-388.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-328.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-315.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-168.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-134.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-197.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-167.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-288.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-329.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-290.jpg", title: "Figure", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-490.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-119.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-439.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-499.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-194.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-234.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-226.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-332.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-385.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-507.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-440.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-275.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-173.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-313.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-137.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-462.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-487.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-148.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-193.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-210.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-390.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-333.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-277.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-165.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-334.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-500.jpg", title: "Abstract", medium: "", price: "Inquire", sold:false, cat:"Abstract" },
  { src: "paintings/susan-544.jpg", title: "The Garden Green", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-545.jpg", title: "Pears on Red", medium: "Acrylic", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-546.jpg", title: "Three Pears", medium: "Acrylic", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-547.jpg", title: "Green Pears", medium: "Acrylic", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-548.jpg", title: "Pair of Pears", medium: "Acrylic", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-549.jpg", title: "Two Pears", medium: "Acrylic", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-550.jpg", title: "Pears, Green and Gold", medium: "Acrylic", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-551.jpg", title: "Ripe Pears", medium: "Acrylic", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-552.jpg", title: "Osprey", medium: "Watercolour", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-553.jpg", title: "Osprey at Rest", medium: "Watercolour", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-554.jpg", title: "Cardinal at the Feeder", medium: "Watercolour", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-555.jpg", title: "Bluebird in the Branches", medium: "Watercolour", price: "Inquire", sold:false, cat:"Animals" },
  { src: "paintings/susan-556.jpg", title: "Sunlit Sea", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-557.jpg", title: "Aloe in a White Pot", medium: "", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-558.jpg", title: "Cherry Blossoms", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-559.jpg", title: "Autumn by the Water", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-560.jpg", title: "Young Girl", medium: "", price: "Inquire", sold:false, cat:"Figures" },
  { src: "paintings/susan-561.jpg", title: "A Day at the Beach", medium: "", price: "Inquire", sold:false, cat:"Beaches" },
  { src: "paintings/susan-562.jpg", title: "Autumn Lake", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-563.jpg", title: "Red Berries", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-564.jpg", title: "Pink Blooms", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-565.jpg", title: "Trailing Ivy", medium: "", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-566.jpg", title: "Aloe on Orange", medium: "", price: "Inquire", sold:false, cat:"Still Life" },
  { src: "paintings/susan-567.jpg", title: "Mountain Lake", medium: "", price: "Inquire", sold:false, cat:"Landscapes" },
  { src: "paintings/susan-568.jpg", title: "Purple Tulips", medium: "", price: "Inquire", sold:false, cat:"Florals" },
  { src: "paintings/susan-569.jpg", title: "Iris", medium: "", price: "Inquire", sold:false, cat:"Florals" },
];
